Neos:
  Neos:
    fusion:
      autoInclude:
        Sitegeist.Kaleidoscope.ValueObjects: true
    Ui:
      resources:
        javascript:
          '@sitegeist/kaleidoscope-valueobjects-plugin':
            resource: 'resource://Sitegeist.Kaleidoscope.ValueObjects/Public/JavaScript/Plugin.js'
    userInterface:
      inspector:
        dataTypes:
          'Sitegeist\Kaleidoscope\ValueObjects\ImageSourceProxy':
            typeConverter: Sitegeist\Kaleidoscope\ValueObjects\TypeConverter\ImageSourceProxyArrayPresenter
            defaultValue: null
            editor: 'Sitegeist.Kaleidoscope.ValueObjects/Inspector/Editors/AssetWithMetadataEditor'
            editorOptions:
              # This is a 1:1 copy of the default image editor settings from Neos
              maximumFileSize: null
              features:
                crop: true
                upload: true
                mediaBrowser: true
                resize: false
              crop:
                aspectRatio:
#                  options:
#                    square:
#                      width: 1
#                      height: 1
#                      label: Square
                  enableOriginal: true
                  allowCustom: true
                  locked:
                    width: 0
                    height: 0
          'Sitegeist\Kaleidoscope\ValueObjects\ImageSourceProxyCollection':
            typeConverter: Sitegeist\Kaleidoscope\ValueObjects\TypeConverter\ImageSourceProxyCollectionArrayPresenter
            defaultValue: []
            editor: 'Sitegeist.Kaleidoscope.ValueObjects/Inspector/Editors/AssetWithMetadataCollectionEditor'
            editorOptions:
              # This is a 1:1 copy of the default image editor settings from Neos
              maximumFileSize: null
              features:
                crop: true
                upload: true
                mediaBrowser: true
                resize: false
              crop:
                aspectRatio:
#                  options:
#                    square:
#                      width: 1
#                      height: 1
#                      label: Square
                  enableOriginal: true
                  allowCustom: true
                  locked:
                    width: 0
                    height: 0
  Fusion:
    defaultContext:
      Sitegeist.Kaleidoscope.ValueObjects: 'Sitegeist\Kaleidoscope\ValueObjects\Eel\ValueObjectHelper'
