Neos:
  Neos:
    Ui:
      resources:
        javascript:
          '@sitegeist/kaleidoscoe-valueobjects':
            resource: 'resource://Sitegeist.Kaleidoscope.ValueObjects/Public/Neos.Ui/Plugin.js'
    userInterface:
      inspector:
        dataTypes:
          'Sitegeist\Kaleidoscope\ValueObjects\AssetWithMetadata':
            editor: 'Sitegeist.Kaleidoscope.ValueObjects/Inspector/Editors/AssetWithMetadata'
          'Sitegeist\Kaleidoscope\ValueObjects\AssetWithMetadataCollection':
            editor: 'Sitegeist.Kaleidoscope.ValueObjects/Inspector/Editors/AssetWithMetadataCollection'

